dist: xenial
language: python
cache: pip
matrix:
  include:
  - os: linux
    sudo: required
    python: 3.5
  - os: linux
    sudo: required
    python: 3.6
  - os: linux
    sudo: required
    python: 3.7
    env: TOXENV=py37
  - os: linux
    sudo: required
    python: pypy3.5-6.0
    env: TOXENV=pypy3
install:
  - pip install tox tox-travis coveralls
script: tox
after_success: coveralls
